# Generated by Django 5.2 on 2025-04-04 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="response",
            old_name="response",
            new_name="text",
        ),
    ]
