# Generated by Django 5.2 on 2025-04-05 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_alter_appointment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
